#!/bin/bash
#	toy_x64_bootloader - Minimal bootloader for x86_64 using long mode and PML4
#	Copyright (C) 2023-2023 Johannes Bauer
#
#	This file is part of toy_x64_bootloader.
#
#	toy_x64_bootloader is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	toy_x64_bootloader is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with toy_x64_bootloader; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

gdb -q -ix .gdbinit -ex "target remote 127.0.0.1:9000" -ex "b *0x7c00" -ex "c"
